"use strict";
/**
 * 浏览器 IIFE 入口
 * esbuild: format=iife, globalName=HealthAnalyzer
 * 产出挂载 window.HealthAnalyzer / globalThis.HealthAnalyzer
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.createL = exports.pickLocale = exports.normalizeLocale = exports.compareSnapshots = exports.buildAnalysisSnapshot = exports.MAIN_PROMPT_TEMPLATE_EN = exports.MAIN_PROMPT_TEMPLATE = exports.SHORT_SYSTEM_PROMPT_EN = exports.SHORT_SYSTEM_PROMPT = exports.formatUserContext = exports.formatAnalysisForLLM = exports.generateDataOnly = exports.generateLLMPrompt = exports.xmlAttr = exports.mergeEcgEntries = exports.workoutTypeLabel = exports.shortWorkoutType = exports.processXmlLine = exports.processWorkoutBlock = exports.RECOVERY_WEIGHT_PRESETS = exports.DEFAULT_RECOVERY_WEIGHTS = exports.attachRecoveryBaseline = exports.summarizeHrvByDay = exports.normalizeRecoveryWeights = exports.recomputeRecovery = exports.calcRecoveryWeeks = exports.calcRecoveryWeek = exports.enrichEcgWithContext = exports.calcEcgStats = exports.calcWorkoutStats = exports.calcWatchStats = exports.calcWeightStats = exports.calcBloodPressureStats = exports.calcCgmStats = exports.analyzeAll = exports.isFutureDate = exports.getLocalToday = exports.parseAppleDate = exports.parseRecordLine = exports.getHour = exports.getDate = exports.finalizeData = exports.processRecord = exports.createEmptyData = exports.extractXmlFromZip = exports.parseEcgCsv = exports.parseBytesStream = exports.parseXmlStream = exports.parseHealthXmlAsync = exports.parseHealthXml = void 0;
exports.calcBpStats = exports.mergeExternalCsvIntoData = exports.parseBloodPressureCsv = exports.parseWeightScaleCsv = exports.generateVisitSummaryMarkdown = exports.generateWeeklyReportMarkdown = exports.joinCsvBundle = exports.buildExportBundle = exports.generateInsightsOnlyPrompt = exports.formatInsightsForLLM = exports.buildInsightBullets = exports.formatCrossSignalsForLLM = exports.detectCrossSignals = exports.traditionalizeAnalysisCopy = exports.traditionalizeMarkdownHeadings = exports.toTraditionalText = exports.toTraditionalTitle = void 0;
var parser_1 = require("./parser");
Object.defineProperty(exports, "parseHealthXml", { enumerable: true, get: function () { return parser_1.parseHealthXml; } });
Object.defineProperty(exports, "parseHealthXmlAsync", { enumerable: true, get: function () { return parser_1.parseHealthXmlAsync; } });
Object.defineProperty(exports, "parseXmlStream", { enumerable: true, get: function () { return parser_1.parseXmlStream; } });
Object.defineProperty(exports, "parseBytesStream", { enumerable: true, get: function () { return parser_1.parseBytesStream; } });
Object.defineProperty(exports, "parseEcgCsv", { enumerable: true, get: function () { return parser_1.parseEcgCsv; } });
Object.defineProperty(exports, "extractXmlFromZip", { enumerable: true, get: function () { return parser_1.extractXmlFromZip; } });
Object.defineProperty(exports, "createEmptyData", { enumerable: true, get: function () { return parser_1.createEmptyData; } });
Object.defineProperty(exports, "processRecord", { enumerable: true, get: function () { return parser_1.processRecord; } });
Object.defineProperty(exports, "finalizeData", { enumerable: true, get: function () { return parser_1.finalizeData; } });
Object.defineProperty(exports, "getDate", { enumerable: true, get: function () { return parser_1.getDate; } });
Object.defineProperty(exports, "getHour", { enumerable: true, get: function () { return parser_1.getHour; } });
Object.defineProperty(exports, "parseRecordLine", { enumerable: true, get: function () { return parser_1.parseRecordLine; } });
Object.defineProperty(exports, "parseAppleDate", { enumerable: true, get: function () { return parser_1.parseAppleDate; } });
Object.defineProperty(exports, "getLocalToday", { enumerable: true, get: function () { return parser_1.getLocalToday; } });
Object.defineProperty(exports, "isFutureDate", { enumerable: true, get: function () { return parser_1.isFutureDate; } });
var stats_1 = require("./stats");
Object.defineProperty(exports, "analyzeAll", { enumerable: true, get: function () { return stats_1.analyzeAll; } });
Object.defineProperty(exports, "calcCgmStats", { enumerable: true, get: function () { return stats_1.calcCgmStats; } });
Object.defineProperty(exports, "calcBloodPressureStats", { enumerable: true, get: function () { return stats_1.calcBloodPressureStats; } });
Object.defineProperty(exports, "calcWeightStats", { enumerable: true, get: function () { return stats_1.calcWeightStats; } });
Object.defineProperty(exports, "calcWatchStats", { enumerable: true, get: function () { return stats_1.calcWatchStats; } });
Object.defineProperty(exports, "calcWorkoutStats", { enumerable: true, get: function () { return stats_1.calcWorkoutStats; } });
Object.defineProperty(exports, "calcEcgStats", { enumerable: true, get: function () { return stats_1.calcEcgStats; } });
Object.defineProperty(exports, "enrichEcgWithContext", { enumerable: true, get: function () { return stats_1.enrichEcgWithContext; } });
Object.defineProperty(exports, "calcRecoveryWeek", { enumerable: true, get: function () { return stats_1.calcRecoveryWeek; } });
Object.defineProperty(exports, "calcRecoveryWeeks", { enumerable: true, get: function () { return stats_1.calcRecoveryWeeks; } });
Object.defineProperty(exports, "recomputeRecovery", { enumerable: true, get: function () { return stats_1.recomputeRecovery; } });
Object.defineProperty(exports, "normalizeRecoveryWeights", { enumerable: true, get: function () { return stats_1.normalizeRecoveryWeights; } });
Object.defineProperty(exports, "summarizeHrvByDay", { enumerable: true, get: function () { return stats_1.summarizeHrvByDay; } });
Object.defineProperty(exports, "attachRecoveryBaseline", { enumerable: true, get: function () { return stats_1.attachRecoveryBaseline; } });
var types_1 = require("./types");
Object.defineProperty(exports, "DEFAULT_RECOVERY_WEIGHTS", { enumerable: true, get: function () { return types_1.DEFAULT_RECOVERY_WEIGHTS; } });
Object.defineProperty(exports, "RECOVERY_WEIGHT_PRESETS", { enumerable: true, get: function () { return types_1.RECOVERY_WEIGHT_PRESETS; } });
var parser_2 = require("./parser");
Object.defineProperty(exports, "processWorkoutBlock", { enumerable: true, get: function () { return parser_2.processWorkoutBlock; } });
Object.defineProperty(exports, "processXmlLine", { enumerable: true, get: function () { return parser_2.processXmlLine; } });
Object.defineProperty(exports, "shortWorkoutType", { enumerable: true, get: function () { return parser_2.shortWorkoutType; } });
Object.defineProperty(exports, "workoutTypeLabel", { enumerable: true, get: function () { return parser_2.workoutTypeLabel; } });
Object.defineProperty(exports, "mergeEcgEntries", { enumerable: true, get: function () { return parser_2.mergeEcgEntries; } });
Object.defineProperty(exports, "xmlAttr", { enumerable: true, get: function () { return parser_2.xmlAttr; } });
var llm_prompt_1 = require("./prompts/llm-prompt");
Object.defineProperty(exports, "generateLLMPrompt", { enumerable: true, get: function () { return llm_prompt_1.generateLLMPrompt; } });
Object.defineProperty(exports, "generateDataOnly", { enumerable: true, get: function () { return llm_prompt_1.generateDataOnly; } });
Object.defineProperty(exports, "formatAnalysisForLLM", { enumerable: true, get: function () { return llm_prompt_1.formatAnalysisForLLM; } });
Object.defineProperty(exports, "formatUserContext", { enumerable: true, get: function () { return llm_prompt_1.formatUserContext; } });
Object.defineProperty(exports, "SHORT_SYSTEM_PROMPT", { enumerable: true, get: function () { return llm_prompt_1.SHORT_SYSTEM_PROMPT; } });
Object.defineProperty(exports, "SHORT_SYSTEM_PROMPT_EN", { enumerable: true, get: function () { return llm_prompt_1.SHORT_SYSTEM_PROMPT_EN; } });
Object.defineProperty(exports, "MAIN_PROMPT_TEMPLATE", { enumerable: true, get: function () { return llm_prompt_1.MAIN_PROMPT_TEMPLATE; } });
Object.defineProperty(exports, "MAIN_PROMPT_TEMPLATE_EN", { enumerable: true, get: function () { return llm_prompt_1.MAIN_PROMPT_TEMPLATE_EN; } });
var snapshot_1 = require("./snapshot");
Object.defineProperty(exports, "buildAnalysisSnapshot", { enumerable: true, get: function () { return snapshot_1.buildAnalysisSnapshot; } });
Object.defineProperty(exports, "compareSnapshots", { enumerable: true, get: function () { return snapshot_1.compareSnapshots; } });
var locale_1 = require("./locale");
Object.defineProperty(exports, "normalizeLocale", { enumerable: true, get: function () { return locale_1.normalizeLocale; } });
Object.defineProperty(exports, "pickLocale", { enumerable: true, get: function () { return locale_1.pickLocale; } });
Object.defineProperty(exports, "createL", { enumerable: true, get: function () { return locale_1.createL; } });
var zh_tw_map_1 = require("./zh-tw-map");
Object.defineProperty(exports, "toTraditionalTitle", { enumerable: true, get: function () { return zh_tw_map_1.toTraditionalTitle; } });
Object.defineProperty(exports, "toTraditionalText", { enumerable: true, get: function () { return zh_tw_map_1.toTraditionalText; } });
Object.defineProperty(exports, "traditionalizeMarkdownHeadings", { enumerable: true, get: function () { return zh_tw_map_1.traditionalizeMarkdownHeadings; } });
Object.defineProperty(exports, "traditionalizeAnalysisCopy", { enumerable: true, get: function () { return zh_tw_map_1.traditionalizeAnalysisCopy; } });
var signals_1 = require("./signals");
Object.defineProperty(exports, "detectCrossSignals", { enumerable: true, get: function () { return signals_1.detectCrossSignals; } });
Object.defineProperty(exports, "formatCrossSignalsForLLM", { enumerable: true, get: function () { return signals_1.formatCrossSignalsForLLM; } });
var insights_1 = require("./insights");
Object.defineProperty(exports, "buildInsightBullets", { enumerable: true, get: function () { return insights_1.buildInsightBullets; } });
Object.defineProperty(exports, "formatInsightsForLLM", { enumerable: true, get: function () { return insights_1.formatInsightsForLLM; } });
Object.defineProperty(exports, "generateInsightsOnlyPrompt", { enumerable: true, get: function () { return insights_1.generateInsightsOnlyPrompt; } });
var export_1 = require("./export");
Object.defineProperty(exports, "buildExportBundle", { enumerable: true, get: function () { return export_1.buildExportBundle; } });
Object.defineProperty(exports, "joinCsvBundle", { enumerable: true, get: function () { return export_1.joinCsvBundle; } });
Object.defineProperty(exports, "generateWeeklyReportMarkdown", { enumerable: true, get: function () { return export_1.generateWeeklyReportMarkdown; } });
Object.defineProperty(exports, "generateVisitSummaryMarkdown", { enumerable: true, get: function () { return export_1.generateVisitSummaryMarkdown; } });
var csv_import_1 = require("./csv-import");
Object.defineProperty(exports, "parseWeightScaleCsv", { enumerable: true, get: function () { return csv_import_1.parseWeightScaleCsv; } });
Object.defineProperty(exports, "parseBloodPressureCsv", { enumerable: true, get: function () { return csv_import_1.parseBloodPressureCsv; } });
Object.defineProperty(exports, "mergeExternalCsvIntoData", { enumerable: true, get: function () { return csv_import_1.mergeExternalCsvIntoData; } });
// 兼容历史 lib.js：calcBpStats 别名
var stats_2 = require("./stats");
Object.defineProperty(exports, "calcBpStats", { enumerable: true, get: function () { return stats_2.calcBloodPressureStats; } });
//# sourceMappingURL=browser.js.map